name: Update demos deps
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  run:
    name: Update demos dependencies
    if: ${{ (github.event_name == 'workflow_dispatch') || (contains(github.event.head_commit.message, 'chore(release)')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Update dependencies
        run: yarn --cwd demos/quasar-ssg-vite upgrade

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: demos/quasar-ssg-vite
          commit-message: "chore(demos-deps): bump dependencies"
          branch: demos/update-deps
          title: update demos deps
