name: Update playground deps
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  run:
    name: Update playground dependencies
    if: ${{ (github.event_name == 'workflow_dispatch') || (contains(github.event.head_commit.message, 'chore(release)')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "pnpm"

      - name: Update dependencies
        run: pnpm --filter quasar-app-extension-ssg-test-vite update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: playground/quasar-cli-with-vite
          commit-message: "chore(playground): bump dependencies"
          branch: playground/update-deps
          title: update playground deps
